// vers_angular/src/app/login/login.component.ts
import { Component } from '@angular/core';
import {FormsModule} from '@angular/forms';
import {AuthService} from '../auth.service';
import {Router} from '@angular/router';

@Component({
  selector: 'app-login',
  imports: [FormsModule],
  standalone : true,
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
  credentials = { email: '', password: '' };

  constructor(private authService: AuthService, private router: Router) { }

  onSubmit(): void {
    this.authService.login(this.credentials.email, this.credentials.password).subscribe({
      next: (users) => {
        if (users.length > 0) {
          this.authService.setLoggedIn(true);
          localStorage.setItem('currentUser', JSON.stringify(users[0]));
          this.router.navigate(['/dashboard']);
        } else {
          alert('Email ou mot de passe incorrect');
        }
      },
      error: (err) => console.error('Erreur connexion', err)
    });
  }
  toggleForm(): void {
    this.router.navigate(['/signup']);
  }

}

<!-- login.component.html -->
<div class="auth-container">
    <div class="auth-card">
      <h2 class="card-title">Connexion</h2>
      <form (ngSubmit)="onSubmit()" class="auth-form">
        <div class="form-group">
          <label for="email">Email</label>
          <input
            type="email"
            id="email"
            [(ngModel)]="credentials.email"
            name="email"
            placeholder="Entrez votre email"
            required>
        </div>
        <div class="form-group">
          <label for="password">Mot de passe</label>
          <input
            type="password"
            id="password"
            [(ngModel)]="credentials.password"
            name="password"
            placeholder="Entrez votre mot de passe"
            required>
        </div>
        <div class="form-actions">
          <button type="submit" class="btn btn-primary">Se connecter</button>
        </div>
        <div class="form-footer">
          <p>Pas encore de compte ? <a (click)="toggleForm()">Créer un compte</a></p>
        </div>
      </form>
    </div>
  </div>

// version_react/src/components/Login.js
import React, { useState, useContext } from 'react';
import { useNavigate } from 'react-router-dom';
import { loginUser } from '../services/authService';
import { AuthContext } from '../context/AuthContext';


const Login = () => {
    const [credentials, setCredentials] = useState({
        email: '',
        password: ''
    });
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);
    const { login } = useContext(AuthContext);
    const navigate = useNavigate();

    const handleChange = (e) => {
        const { name, value } = e.target;
        setCredentials({
            ...credentials,
            [name]: value
        });
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);
        setError('');

        try {
            const user = await loginUser(credentials);
            login(user);
            navigate('/');
        } catch (error) {
            setError(error.message);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="auth-container">
            <div className="auth-header">
                <h1>Connexion</h1>
            </div>
            
            <div className="auth-form">
                {error && <div className="error-message">{error}</div>}
                <form onSubmit={handleSubmit}>
                    <div className="form-group">
                        <label htmlFor="email">Email</label>
                        <input
                            type="email"
                            id="email"
                            name="email"
                            value={credentials.email}
                            onChange={handleChange}
                            required
                            placeholder="Votre email"
                            className="form-input"
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="password">Mot de passe</label>
                        <input
                            type="password"
                            id="password"
                            name="password"
                            value={credentials.password}
                            onChange={handleChange}
                            required
                            placeholder="Votre mot de passe"
                            className="form-input"
                        />
                    </div>
                    <div className="form-options">
                        <label className="remember-me">
                            <input type="checkbox" /> Se souvenir de moi
                        </label>
                        <a href="/forgot-password" className="forgot-password">
                            Mot de passe oublié?
                        </a>
                    </div>
                    <button type="submit" className="auth-button" disabled={loading}>
                        {loading ? 'Connexion en cours...' : 'Se connecter'}
                    </button>
                </form>
                <div className="auth-redirect">
                    Pas encore de compte? <a href="/signup">Inscrivez-vous</a>
                </div>
            </div>
        </div>
    );
};

export default Login;
